// <auto-generated />
using System;
using CollectionManagerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollectionManagerApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260615080345_FixedCascadePaths")]
    partial class FixedCascadePaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollectionManagerApi.Models.Chatroom", b =>
                {
                    b.Property<int>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationID"));

                    b.Property<int>("ConversationUser1ID")
                        .HasColumnType("int");

                    b.Property<int>("ConversationUser2ID")
                        .HasColumnType("int");

                    b.Property<int?>("ListingID")
                        .HasColumnType("int");

                    b.HasKey("ConversationID");

                    b.HasIndex("ListingID");

                    b.ToTable("Chatroom");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.ChatroomMessage", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<int>("ConversationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MessageSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MessageID");

                    b.HasIndex("ConversationID");

                    b.HasIndex("UserID");

                    b.ToTable("ChatroomMessage");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Chatroom_User", b =>
                {
                    b.Property<int>("ConversationID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ConversationID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("Junction_Chatroom_User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Collection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectionId"));

                    b.Property<string>("CollectionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CollectionId");

                    b.HasIndex("UserID");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.CollectionFolder", b =>
                {
                    b.Property<int>("CollectionFolderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectionFolderID"));

                    b.Property<string>("CollectionFolderDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollectionFolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CollectionFolderID");

                    b.HasIndex("UserID");

                    b.ToTable("CollectionFolder");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.CollectionFolder_Collection", b =>
                {
                    b.Property<int>("CollectionFolderID")
                        .HasColumnType("int");

                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.HasKey("CollectionFolderID", "CollectionID");

                    b.HasIndex("CollectionID");

                    b.ToTable("Junction_Folder_Collection");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int?>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ItemPurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemValue")
                        .HasColumnType("int");

                    b.Property<int?>("PictureID")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.HasIndex("PictureID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Item_Collection", b =>
                {
                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.HasKey("ItemID", "CollectionID");

                    b.HasIndex("CollectionID");

                    b.ToTable("Junction_Item_Collection");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.MarketplaceListing", b =>
                {
                    b.Property<int>("ListingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingID"));

                    b.Property<string>("DescriptionOfListing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<bool>("ItemIsRequested")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ListingCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ListingIsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ListingID");

                    b.HasIndex("ItemID");

                    b.HasIndex("UserID");

                    b.ToTable("Marketplace");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Picture", b =>
                {
                    b.Property<int>("PictureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PictureID"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PictureID");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.ShoppingLink", b =>
                {
                    b.Property<int>("ShoppingLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingLinkID"));

                    b.Property<bool>("ShoppingLinkIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShoppingLinkTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShoppingLinkUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ShoppingLinkID");

                    b.HasIndex("UserID");

                    b.ToTable("ShoppingLink");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.UserLogin", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.UserProfile", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<bool>("AdminUserType")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PictureID")
                        .HasColumnType("int");

                    b.Property<string>("UserDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("PictureID");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Wishlist", b =>
                {
                    b.Property<int>("WishlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistID"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("WishlistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WishlistID");

                    b.HasIndex("UserID");

                    b.ToTable("Wishlist");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Wishlist_Item", b =>
                {
                    b.Property<int>("WishlistID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.HasKey("WishlistID", "ItemID");

                    b.HasIndex("ItemID");

                    b.ToTable("Junction_Wishlist_Item");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Chatroom", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.MarketplaceListing", "MarketplaceListing")
                        .WithMany("Chatroom")
                        .HasForeignKey("ListingID");

                    b.Navigation("MarketplaceListing");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.ChatroomMessage", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.Chatroom", "Chatroom")
                        .WithMany("ChatroomMessage")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollectionManagerApi.Models.User", "User")
                        .WithMany("ChatroomMessage")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chatroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Chatroom_User", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.Chatroom", "Chatroom")
                        .WithMany("Chatroom_User")
                        .HasForeignKey("ConversationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollectionManagerApi.Models.User", "User")
                        .WithMany("Chatroom_User")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chatroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Collection", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.User", "User")
                        .WithMany("Collection")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.CollectionFolder", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.User", "User")
                        .WithMany("CollectionFolder")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.CollectionFolder_Collection", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.CollectionFolder", "CollectionFolder")
                        .WithMany("CollectionFolder_Collection")
                        .HasForeignKey("CollectionFolderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CollectionManagerApi.Models.Collection", "Collection")
                        .WithMany("CollectionFolder_Collection")
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("CollectionFolder");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Item", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.Picture", "Picture")
                        .WithMany("Item")
                        .HasForeignKey("PictureID");

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Item_Collection", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.Collection", "Collection")
                        .WithMany("Item_Collection")
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollectionManagerApi.Models.Item", "Item")
                        .WithMany("Item_Collection")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.MarketplaceListing", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.Item", "Item")
                        .WithMany("MarketplaceListing")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollectionManagerApi.Models.User", "User")
                        .WithMany("MarketplaceListing")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.ShoppingLink", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.User", "User")
                        .WithMany("ShoppingLink")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.UserLogin", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.User", "User")
                        .WithOne("UserLogin")
                        .HasForeignKey("CollectionManagerApi.Models.UserLogin", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.UserProfile", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.Picture", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureID");

                    b.HasOne("CollectionManagerApi.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("CollectionManagerApi.Models.UserProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Picture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Wishlist", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.User", "User")
                        .WithMany("Wishlist")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Wishlist_Item", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.Item", "Item")
                        .WithMany("Wishlist_Item")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CollectionManagerApi.Models.Wishlist", "Wishlist")
                        .WithMany("Wishlist_Item")
                        .HasForeignKey("WishlistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Chatroom", b =>
                {
                    b.Navigation("ChatroomMessage");

                    b.Navigation("Chatroom_User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Collection", b =>
                {
                    b.Navigation("CollectionFolder_Collection");

                    b.Navigation("Item_Collection");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.CollectionFolder", b =>
                {
                    b.Navigation("CollectionFolder_Collection");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Item", b =>
                {
                    b.Navigation("Item_Collection");

                    b.Navigation("MarketplaceListing");

                    b.Navigation("Wishlist_Item");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.MarketplaceListing", b =>
                {
                    b.Navigation("Chatroom");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Picture", b =>
                {
                    b.Navigation("Item");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.User", b =>
                {
                    b.Navigation("ChatroomMessage");

                    b.Navigation("Chatroom_User");

                    b.Navigation("Collection");

                    b.Navigation("CollectionFolder");

                    b.Navigation("MarketplaceListing");

                    b.Navigation("ShoppingLink");

                    b.Navigation("UserLogin")
                        .IsRequired();

                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("Wishlist");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Wishlist", b =>
                {
                    b.Navigation("Wishlist_Item");
                });
#pragma warning restore 612, 618
        }
    }
}
