// <auto-generated />
using System;
using CollectionManagerApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollectionManagerApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260604085223_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollectionManagerApi.Models.ChatroomMessageModel", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<int?>("ChatroomModelConversationID")
                        .HasColumnType("int");

                    b.Property<int>("ConversationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MessageSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MessageID");

                    b.HasIndex("ChatroomModelConversationID");

                    b.ToTable("ChatroomMessage");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.ChatroomModel", b =>
                {
                    b.Property<int>("ConversationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationID"));

                    b.Property<int>("ConversationUser1ID")
                        .HasColumnType("int");

                    b.Property<int>("ConversationUser2ID")
                        .HasColumnType("int");

                    b.Property<int>("ListingID")
                        .HasColumnType("int");

                    b.HasKey("ConversationID");

                    b.ToTable("Chatroom");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Chatroom_UserModel", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("ConversationID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "ConversationID");

                    b.ToTable("Junction_Chatroom_User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.CollectionFolderModel", b =>
                {
                    b.Property<int>("CollectionFolderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectionFolderID"));

                    b.Property<string>("CollectionFolderDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollectionFolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CollectionFolderID");

                    b.ToTable("ColelctionFolder");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.CollectionFolder_CollectionModel", b =>
                {
                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.Property<int>("CollectionFolderID")
                        .HasColumnType("int");

                    b.HasKey("CollectionID", "CollectionFolderID");

                    b.ToTable("Junction_Folder_Collection");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.CollectionModel", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectionId"));

                    b.Property<string>("CollectionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CollectionFolderModelCollectionFolderID")
                        .HasColumnType("int");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CollectionId");

                    b.HasIndex("CollectionFolderModelCollectionFolderID");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.ItemModel", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<int?>("CollectionModelCollectionId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemCount")
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ItemPurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemValue")
                        .HasColumnType("int");

                    b.Property<int?>("PictureID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("WishlistModelUserID")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.HasIndex("CollectionModelCollectionId");

                    b.HasIndex("PictureID");

                    b.HasIndex("WishlistModelUserID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Item_CollectionModel", b =>
                {
                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.HasKey("ItemID", "CollectionID");

                    b.ToTable("Junction_Item_Collection");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.MarketplaceListingModel", b =>
                {
                    b.Property<int>("ListingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListingID"));

                    b.Property<string>("DescriptionOfListing")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<bool>("ItemIsRequested")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ListingCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ListingIsActive")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ListingID");

                    b.ToTable("Marketplace");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.PictureModel", b =>
                {
                    b.Property<int>("PictureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PictureID"));

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PictureID");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.ShoppingLinkModel", b =>
                {
                    b.Property<int>("ShoppingLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingLinkID"));

                    b.Property<bool>("ShoppingLinkIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShoppingLinkTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShoppingLinkUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ShoppingLinkID");

                    b.ToTable("ShoppingLink");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.UserLoginModel", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("UserLogin");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.UserProfileModel", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<bool>("AdminUserType")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PictureID")
                        .HasColumnType("int");

                    b.Property<string>("UserDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.HasIndex("PictureID");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.WishlistModel", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.HasKey("UserID");

                    b.ToTable("Wishlist");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.Wishlist_ItemModel", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "ItemID");

                    b.ToTable("Junction_Wishlist_Item");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.ChatroomMessageModel", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.ChatroomModel", null)
                        .WithMany("MessagesInConversation")
                        .HasForeignKey("ChatroomModelConversationID");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.CollectionModel", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.CollectionFolderModel", null)
                        .WithMany("CollectionsInFolder")
                        .HasForeignKey("CollectionFolderModelCollectionFolderID");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.ItemModel", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.CollectionModel", null)
                        .WithMany("ItemsInCollection")
                        .HasForeignKey("CollectionModelCollectionId");

                    b.HasOne("CollectionManagerApi.Models.PictureModel", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureID");

                    b.HasOne("CollectionManagerApi.Models.WishlistModel", null)
                        .WithMany("ItemsInWishlist")
                        .HasForeignKey("WishlistModelUserID");

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.UserProfileModel", b =>
                {
                    b.HasOne("CollectionManagerApi.Models.PictureModel", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureID");

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.ChatroomModel", b =>
                {
                    b.Navigation("MessagesInConversation");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.CollectionFolderModel", b =>
                {
                    b.Navigation("CollectionsInFolder");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.CollectionModel", b =>
                {
                    b.Navigation("ItemsInCollection");
                });

            modelBuilder.Entity("CollectionManagerApi.Models.WishlistModel", b =>
                {
                    b.Navigation("ItemsInWishlist");
                });
#pragma warning restore 612, 618
        }
    }
}
